on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: # Enables on-demand/manual triggering
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install -q requests
          python src/all.py | jq . --tab > all.json
          python src/open.py | jq . --tab > open.json
          python src/extreme.py | jq . --tab > extreme.json
          python src/losses.py | jq . --tab > losses.json
          python src/soon.py | jq . --tab > soon.json
          python src/whales.py | jq . --tab > whales.json
          python src/users.py | jq . --tab > users.json
          python src/ce.py > ce.txt
          # python src/bet.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
      - uses: peter-evans/create-pull-request@v6
        with:
          commit-message: market update
          title: market update
          delete-branch: true
