on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: # Enables on-demand/manual triggering
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install -q requests
          python src/extreme.py | jq . --tab > extreme.json
          python src/ce.py > ce.txt
          python src/markets.py
          python src/users.py
          rm all.json
          sed -i '/[Aa]vatarUrl": "/d' *.json
          # python src/bet.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
      - uses: peter-evans/create-pull-request@v6
        with:
          commit-message: market update
          title: market update
          delete-branch: true
