on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: # Enables on-demand/manual triggering
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3
      - run: |
          pip install -q requests
          python src/all.py | jq . > all.json
          python src/open.py | jq . > open.json
          python src/extreme.py | jq . > extreme.json
          python src/losses.py | jq . > losses.json
          python src/soon.py | jq . > soon.json
          python src/whales.py | jq . > whales.json
          python src/users.py | jq . > users.json
          python src/bet.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
      - uses: peter-evans/create-pull-request@v3
        with:
          commit-message: market update
          title: market update
          delete-branch: true
